CREATE USER sample
  IDENTIFIED BY samplepw
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
/
 
GRANT DBA TO SAMPLE;
GRANT UNLIMITED TABLESPACE TO SAMPLE;


CREATE TABLE SAMPLE.BLOG (
 ID NUMBER(10, 0) NOT NULL,
 NAME NVARCHAR2(50)
);

INSERT INTO SAMPLE.BLOG VALUES ('1', 'Test001');
INSERT INTO SAMPLE.BLOG VALUES ('2', 'Test002');
INSERT INTO SAMPLE.BLOG VALUES ('3', 'Test003');
